# Generated by Django 6.1 on 2026-08-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_entry_deposit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='entry_has_exactly_one_origin',
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit__isnull', True), ('transfer__isnull', False)), models.Q(('deposit__isnull', False), ('transfer__isnull', True)), _connector='OR'), name='entry_has_exactly_one_origin'),
        ),
    ]
